local L = LibStub("AceLocale-3.0"):NewLocale("BetterCooldownManager", "koKR")
if not L then return end

-- [[ Tabs ]]
L["General"] = "일반"
L["Global"] = "전역"
L["Edit Mode Manager"] = "편집 모드"
L["Essential"] = "핵심 능력"
L["Utility"] = "보조 능력"
L["Buffs"] = "강화 효과"
L["Custom"] = "사용자"
L["Additional Custom"] = "추가 사용자"
L["Item"] = "아이템"
L["Trinkets"] = "장신구"
L["Items & Spells"] = "템 / 주문"
L["Power Bar"] = "자원 바"
L["Secondary Power Bar"] = "보조 자원 바"
L["Cast Bar"] = "시전 바"
L["Profiles"] = "프로필"

-- [[ GUI Options & Text ]]
L["Icon Size"] = "아이콘 크기"
L["The size of the icons."] = "표시될 아이콘의 크기를 설정합니다."
L["Bar Width"] = "바 너비"
L["Bar Height"] = "바 높이"
L["Font Size"] = "글꼴 크기"
L["Spacing"] = "간격"
L["Show Text"] = "텍스트 표시"
L["Enable"] = "활성화"
L["Lock Anchor"] = "위치 고정"

-- [[ Resources & Powers ]]
L["Mana"] = "마나"
L["Rage"] = "분노"
L["Focus"] = "집중"
L["Energy"] = "기력"
L["Combo Points"] = "연계 점수"
L["Runes"] = "룬"
L["Runic Power"] = "룬 마력"
L["Soul Shards"] = "영혼 조각"
L["Astral Power"] = "천공의 힘"
L["Holy Power"] = "신성한 힘"
L["Maelstrom"] = "소용돌이"
L["Chi"] = "기"
L["Insanity"] = "광기"
L["Arcane Charges"] = "비전 충전물"
L["Fury"] = "분노"
L["Pain"] = "고통"
L["Essence"] = "정수"
L["Stagger"] = "시간차"